"""fresh start

Revision ID: 51e104081b97
Revises: 
Create Date: 2026-04-14 13:22:54.878824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51e104081b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=500), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('organization_type', sa.String(length=300), nullable=True),
    sa.Column('ministry', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=500), nullable=True),
    sa.Column('organization_name', sa.String(length=800), nullable=True),
    sa.Column('office_zone', sa.String(length=800), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('buyer_designation', sa.String(length=300), nullable=True),
    sa.Column('buying_mode', sa.String(length=200), nullable=True),
    sa.Column('bid_number', sa.String(length=200), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('brands', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=255), nullable=False),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('msme_reg_no', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('ucfd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('organization_type', sa.String(length=100), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('office_zone', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('buyer_designation', sa.String(length=100), nullable=True),
    sa.Column('buying_mode', sa.String(length=100), nullable=True),
    sa.Column('bid_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('service', sa.String(length=512), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('hsn_code', sa.String(length=100), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('msme_reg_no', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status', 'organization_type', 'ministry', 'department', 'organization_name', 'office_zone', 'location', 'buyer_designation', 'buying_mode', 'bid_number', 'contract_date', 'total', 'service', 'product', 'brand', 'model', 'hsn_code', 'ordered_quantity', 'price', 'generated_date', 'category_name', 'seller_id', 'company_name', 'contact_no', 'email', 'address', 'msme_reg_no', 'gstin', name='ucfd_unique_combo')
    )
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category_names', sa.Text(), nullable=True),
    sa.Column('brand_names', sa.Text(), nullable=True),
    sa.Column('assigned_date_range_start', sa.Date(), nullable=True),
    sa.Column('assigned_date_range_end', sa.Date(), nullable=True),
    sa.Column('subscription_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_history')
    op.drop_table('ucfd')
    op.drop_table('sellers')
    op.drop_table('contracts')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
