"""add service start and end dates to sellers table

Revision ID: 8ef04fe70c26
Revises: 51e104081b97
Create Date: 2026-05-21 13:08:01.468620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef04fe70c26'
down_revision = '51e104081b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('service_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('service_end_date')
        batch_op.drop_column('service_start_date')

    # ### end Alembic commands ###
